GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsImlhdCI6MTY5NDU3Nzc0OSwiZXhwIjoxNjk0NTc4NjQ5fQ.pZwiaRLOCacZd8KNIfldD3b4pAPi-TYLpQ_Q9iV0vNQ

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "doe2",
    "email": "doe2@gmail.com",
    "password": "password",
    "confPassword": "password"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "password"
}

###
GET http://localhost:5000/token

